// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Waze2
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Search For Whitworth and select the option when it pops up
        /// </summary>
        public void SearchOnWhitworth()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(120, 194));

            // Type 'Whitworth ' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.SearchOnWhitworthParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(162, 217));
        }
        
        /// <summary>
        /// Look for directions from Whitworth to London
        /// </summary>
        public void SearchOverSeas()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(151, 189));

            // Type 'Whitworth {RShiftKey}University' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.SearchOverSeasParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(255, 229));

            // Type 'London ' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.SearchOverSeasParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(196, 250));
        }
        
        /// <summary>
        /// Try to Search to get to Florida Keys from Cuba
        /// </summary>
        public void GoToCuba()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(118, 187));

            // Type 'Cuba {RShiftKey}Ha' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.GoToCubaParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Type 'vana{Enter}' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.GoToCubaParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(137, 221));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(135, 218));

            // Type 'Florida {RShiftKey}Keys' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.GoToCubaParams.UIChromeLegacyWindowDocumentSendKeys2, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(151, 302));
        }
        
        /// <summary>
        /// Try to go between two of the hawaiian islands
        /// </summary>
        public void InterHawaii()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(197, 178));

            // Type 'Marriot {RShiftKey}Ka' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.InterHawaiiParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(187, 279));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(191, 222));

            // Type 'Marriott ' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.InterHawaiiParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Type 'Oahu' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.InterHawaiiParams.UIChromeLegacyWindowDocumentSendKeys2, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(236, 267));
        }
        
        /// <summary>
        /// This gets directions between costco in the valley and whitworth
        /// </summary>
        public void GoToCostco()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(160, 187));

            // Type 'Costco' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.GoToCostcoParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(171, 221));

            // Type 'Whitworth ' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.GoToCostcoParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(176, 257));
        }
        
        /// <summary>
        /// Attempts to get directions from two on campus buildings
        /// </summary>
        public void BetweenBuildings()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(146, 186));

            // Type 'Eric {RShiftKey}Johnston {RShiftKey}Science {RShiftKey}Center{Enter}' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.BetweenBuildingsParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(151, 224));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(147, 219));

            // Type 'Robinson ' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.BetweenBuildingsParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(176, 258));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(393, 225));
        }
        
        /// <summary>
        /// This gets directions that leave the country from Whitworth to Nelson Canada
        /// </summary>
        public void GoToCanada()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(168, 177));

            // Type 'Whitworth' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.GoToCanadaParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(190, 225));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(190, 225));

            // Type 'Nelson ' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.GoToCanadaParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(186, 254));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(388, 222));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(108, 259));
        }
        
        #region Properties
        public virtual SearchOnWhitworthParams SearchOnWhitworthParams
        {
            get
            {
                if ((this.mSearchOnWhitworthParams == null))
                {
                    this.mSearchOnWhitworthParams = new SearchOnWhitworthParams();
                }
                return this.mSearchOnWhitworthParams;
            }
        }
        
        public virtual SearchOverSeasParams SearchOverSeasParams
        {
            get
            {
                if ((this.mSearchOverSeasParams == null))
                {
                    this.mSearchOverSeasParams = new SearchOverSeasParams();
                }
                return this.mSearchOverSeasParams;
            }
        }
        
        public virtual GoToCubaParams GoToCubaParams
        {
            get
            {
                if ((this.mGoToCubaParams == null))
                {
                    this.mGoToCubaParams = new GoToCubaParams();
                }
                return this.mGoToCubaParams;
            }
        }
        
        public virtual InterHawaiiParams InterHawaiiParams
        {
            get
            {
                if ((this.mInterHawaiiParams == null))
                {
                    this.mInterHawaiiParams = new InterHawaiiParams();
                }
                return this.mInterHawaiiParams;
            }
        }
        
        public virtual GoToCostcoParams GoToCostcoParams
        {
            get
            {
                if ((this.mGoToCostcoParams == null))
                {
                    this.mGoToCostcoParams = new GoToCostcoParams();
                }
                return this.mGoToCostcoParams;
            }
        }
        
        public virtual BetweenBuildingsParams BetweenBuildingsParams
        {
            get
            {
                if ((this.mBetweenBuildingsParams == null))
                {
                    this.mBetweenBuildingsParams = new BetweenBuildingsParams();
                }
                return this.mBetweenBuildingsParams;
            }
        }
        
        public virtual GoToCanadaParams GoToCanadaParams
        {
            get
            {
                if ((this.mGoToCanadaParams == null))
                {
                    this.mGoToCanadaParams = new GoToCanadaParams();
                }
                return this.mGoToCanadaParams;
            }
        }
        
        public UITrafficJamNewsUpdateWindow UITrafficJamNewsUpdateWindow
        {
            get
            {
                if ((this.mUITrafficJamNewsUpdateWindow == null))
                {
                    this.mUITrafficJamNewsUpdateWindow = new UITrafficJamNewsUpdateWindow();
                }
                return this.mUITrafficJamNewsUpdateWindow;
            }
        }
        #endregion
        
        #region Fields
        private SearchOnWhitworthParams mSearchOnWhitworthParams;
        
        private SearchOverSeasParams mSearchOverSeasParams;
        
        private GoToCubaParams mGoToCubaParams;
        
        private InterHawaiiParams mInterHawaiiParams;
        
        private GoToCostcoParams mGoToCostcoParams;
        
        private BetweenBuildingsParams mBetweenBuildingsParams;
        
        private GoToCanadaParams mGoToCanadaParams;
        
        private UITrafficJamNewsUpdateWindow mUITrafficJamNewsUpdateWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SearchOnWhitworth'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class SearchOnWhitworthParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Whitworth ' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Whitworth ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SearchOverSeas'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class SearchOverSeasParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Whitworth {RShiftKey}University' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Whitworth {RShiftKey}University";
        
        /// <summary>
        /// Type 'London ' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "London ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'GoToCuba'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class GoToCubaParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Cuba {RShiftKey}Ha' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Cuba {RShiftKey}Ha";
        
        /// <summary>
        /// Type 'vana{Enter}' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "vana{Enter}";
        
        /// <summary>
        /// Type 'Florida {RShiftKey}Keys' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys2 = "Florida {RShiftKey}Keys";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'InterHawaii'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class InterHawaiiParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Marriot {RShiftKey}Ka' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Marriot {RShiftKey}Ka";
        
        /// <summary>
        /// Type 'Marriott ' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "Marriott ";
        
        /// <summary>
        /// Type 'Oahu' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys2 = "Oahu";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'GoToCostco'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class GoToCostcoParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Costco' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Costco";
        
        /// <summary>
        /// Type 'Whitworth ' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "Whitworth ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'BetweenBuildings'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class BetweenBuildingsParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Eric {RShiftKey}Johnston {RShiftKey}Science {RShiftKey}Center{Enter}' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Eric {RShiftKey}Johnston {RShiftKey}Science {RShiftKey}Center{Enter}";
        
        /// <summary>
        /// Type 'Robinson ' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "Robinson ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'GoToCanada'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class GoToCanadaParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Whitworth' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Whitworth";
        
        /// <summary>
        /// Type 'Nelson ' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "Nelson ";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITrafficJamNewsUpdateWindow : WinWindow
    {
        
        public UITrafficJamNewsUpdateWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Traffic Jam News, Updates from the Road - Waze Live Map - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Traffic Jam News, Updates from the Road - Waze Live Map - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinWindow UITrafficJamNewsUpdateWindow1
        {
            get
            {
                if ((this.mUITrafficJamNewsUpdateWindow1 == null))
                {
                    this.mUITrafficJamNewsUpdateWindow1 = new WinWindow(this);
                    #region Search Criteria
                    this.mUITrafficJamNewsUpdateWindow1.SearchProperties[WinWindow.PropertyNames.Name] = "Traffic Jam News, Updates from the Road - Waze Live Map";
                    this.mUITrafficJamNewsUpdateWindow1.WindowTitles.Add("Traffic Jam News, Updates from the Road - Waze Live Map - Google Chrome");
                    #endregion
                }
                return this.mUITrafficJamNewsUpdateWindow1;
            }
        }
        
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUITrafficJamNewsUpdateWindow1;
        
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Chrome Legacy Window";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_RenderWidgetHostHWND";
            this.WindowTitles.Add("Traffic Jam News, Updates from the Road - Waze Live Map - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Traffic Jam News, Updates from the Road - Waze Live Map - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
}
