// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Waze2
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Search For Whitworth and select the option when it pops up
        /// </summary>
        public void SearchOnWhitworth()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(120, 194));

            // Type 'Whitworth ' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.SearchOnWhitworthParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(162, 217));
        }
        
        /// <summary>
        /// Look for directions from Whitworth to London
        /// </summary>
        public void SearchOverSeas()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(151, 189));

            // Type 'Whitworth {RShiftKey}University' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.SearchOverSeasParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(255, 229));

            // Type 'London ' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.SearchOverSeasParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(196, 250));
        }
        
        /// <summary>
        /// Try to Search to get to Florida Keys from Cuba
        /// </summary>
        public void GoToCuba()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(118, 187));

            // Type 'Cuba {RShiftKey}Ha' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.GoToCubaParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Type 'vana{Enter}' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.GoToCubaParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(137, 221));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(135, 218));

            // Type 'Florida {RShiftKey}Keys' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.GoToCubaParams.UIChromeLegacyWindowDocumentSendKeys2, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(151, 302));
        }
        
        /// <summary>
        /// Try to go between two of the hawaiian islands
        /// </summary>
        public void InterHawaii()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(197, 178));

            // Type 'Marriot {RShiftKey}Ka' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.InterHawaiiParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(187, 279));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(191, 222));

            // Type 'Marriott ' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.InterHawaiiParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Type 'Oahu' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.InterHawaiiParams.UIChromeLegacyWindowDocumentSendKeys2, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(236, 267));
        }
        
        /// <summary>
        /// This gets directions between costco in the valley and whitworth
        /// </summary>
        public void GoToCostco()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(160, 187));

            // Type 'Costco' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.GoToCostcoParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(171, 221));

            // Type 'Whitworth ' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.GoToCostcoParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(176, 257));
        }
        
        /// <summary>
        /// Attempts to get directions from two on campus buildings
        /// </summary>
        public void BetweenBuildings()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(146, 186));

            // Type 'Eric {RShiftKey}Johnston {RShiftKey}Science {RShiftKey}Center{Enter}' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.BetweenBuildingsParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(151, 224));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(147, 219));

            // Type 'Robinson ' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.BetweenBuildingsParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(176, 258));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(393, 225));
        }
        
        /// <summary>
        /// This gets directions that leave the country from Whitworth to Nelson Canada
        /// </summary>
        public void GoToCanada()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(168, 177));

            // Type 'Whitworth' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.GoToCanadaParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(190, 225));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(190, 225));

            // Type 'Nelson ' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.GoToCanadaParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(186, 254));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(388, 222));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(108, 259));
        }
        
        /// <summary>
        /// This searches between Seattle University and an island that requires a ferry
        /// </summary>
        public void FerryRun()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(146, 194));

            // Type 'Seattle {RShiftKey}University' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.FerryRunParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(169, 286));

            // Type 'whid' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.FerryRunParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(120, 252));
        }
        
        /// <summary>
        /// Looks to see how waze interacts with a military base
        /// </summary>
        public void FortSearch()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(133, 193));

            // Type 'Parade {RShiftKey}Field' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.FortSearchParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(200, 215));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(152, 211));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(145, 219));

            // Type 'Odenton {RShiftKey}Marc' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.FortSearchParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(225, 261));
        }
        
        /// <summary>
        /// This searches between Whitworth and Santa Clara University
        /// </summary>
        public void WhitToSantaClara()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(137, 189));

            // Type 'Whitworth {RShiftKey}Univer' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.WhitToSantaClaraParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(179, 225));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(165, 222));

            // Type 'Santa {RShiftKey}Clara {RShiftKey}Un' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.WhitToSantaClaraParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(181, 382));
        }
        
        /// <summary>
        /// Tests N/S distance from Whitworth to Scripps
        /// </summary>
        public void WhitToScripps()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(105, 181));

            // Type 'Whitworth {RShiftKey}University' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.WhitToScrippsParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(160, 235));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(111, 218));

            // Type 'Scripps {RShiftKey}Co' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.WhitToScrippsParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(135, 260));
        }
        
        /// <summary>
        /// Searches for distance between whitworth and san diego
        /// </summary>
        public void WhitToSanDiego()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(171, 195));

            // Type 'Whitworth' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.WhitToSanDiegoParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(173, 212));

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(130, 219));

            // Type 'University of {RShiftKey}San {RShiftKey}D' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.WhitToSanDiegoParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(197, 253));
        }
        
        /// <summary>
        /// Trys to get directions from Whitworth to University of Maryland
        /// </summary>
        public void EastWest()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(141, 183));

            // Type 'Whitworth {RShiftKey}University' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.EastWestParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(180, 241));

            // Type 'University of {RShiftKey}Maryland' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.EastWestParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(263, 256));
        }
        
        /// <summary>
        /// Opens Waze
        /// </summary>
        public void OpenWazeWebsite()
        {
            #region Variable Declarations
            WinEdit uIAddressandsearchbarEdit = this.UINewTabGoogleChromeWindow.UIItemGroup.UIAddressandsearchbarEdit;
            #endregion

            // Click 'Address and search bar' text box
            Mouse.Click(uIAddressandsearchbarEdit, new Point(102, 12));

            // Type 'www.waze.com/livemap{Enter}' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, this.OpenWazeWebsiteParams.UIAddressandsearchbarEditSendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// OpenWaze2 - Use 'OpenWaze2Params' to pass parameters into this method.
        /// </summary>
        public void OpenWaze2()
        {
            #region Variable Declarations
            WinEdit uIAddressandsearchbarEdit = this.UINewTabGoogleChromeWindow.UIItemGroup.UIAddressandsearchbarEdit;
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            #endregion

            // Click 'Address and search bar' text box
            Mouse.Click(uIAddressandsearchbarEdit, new Point(41, 7));

            // Type 'www.waze.com/livemap{Enter}' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, this.OpenWaze2Params.UIAddressandsearchbarEditSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(127, 210));
        }
        
        /// <summary>
        /// Whitworth2 - Use 'Whitworth2Params' to pass parameters into this method.
        /// </summary>
        public void Whitworth2()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow1.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(226, 206));

            // Type 'Whitworth {RShiftKey}Univeri{Back}sity' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.Whitworth2Params.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(220, 258));
        }
        
        /// <summary>
        /// Whitworth3 - Use 'Whitworth3Params' to pass parameters into this method.
        /// </summary>
        public void Whitworth3()
        {
            #region Variable Declarations
            WinEdit uIAddressandsearchbarEdit = this.UINewTabGoogleChromeWindow.UIItemGroup.UIAddressandsearchbarEdit;
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            #endregion

            // Click 'Address and search bar' text box
            Mouse.Click(uIAddressandsearchbarEdit, new Point(79, 9));

            // Type 'www.waze.com/livemap{Enter}' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, this.Whitworth3Params.UIAddressandsearchbarEditSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(177, 215));

            // Type 'Whitworth {RShiftKey}Un' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, this.Whitworth3Params.UIAddressandsearchbarEditSendKeys1, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(227, 257));
        }
        
        #region Properties
        public virtual SearchOnWhitworthParams SearchOnWhitworthParams
        {
            get
            {
                if ((this.mSearchOnWhitworthParams == null))
                {
                    this.mSearchOnWhitworthParams = new SearchOnWhitworthParams();
                }
                return this.mSearchOnWhitworthParams;
            }
        }
        
        public virtual SearchOverSeasParams SearchOverSeasParams
        {
            get
            {
                if ((this.mSearchOverSeasParams == null))
                {
                    this.mSearchOverSeasParams = new SearchOverSeasParams();
                }
                return this.mSearchOverSeasParams;
            }
        }
        
        public virtual GoToCubaParams GoToCubaParams
        {
            get
            {
                if ((this.mGoToCubaParams == null))
                {
                    this.mGoToCubaParams = new GoToCubaParams();
                }
                return this.mGoToCubaParams;
            }
        }
        
        public virtual InterHawaiiParams InterHawaiiParams
        {
            get
            {
                if ((this.mInterHawaiiParams == null))
                {
                    this.mInterHawaiiParams = new InterHawaiiParams();
                }
                return this.mInterHawaiiParams;
            }
        }
        
        public virtual GoToCostcoParams GoToCostcoParams
        {
            get
            {
                if ((this.mGoToCostcoParams == null))
                {
                    this.mGoToCostcoParams = new GoToCostcoParams();
                }
                return this.mGoToCostcoParams;
            }
        }
        
        public virtual BetweenBuildingsParams BetweenBuildingsParams
        {
            get
            {
                if ((this.mBetweenBuildingsParams == null))
                {
                    this.mBetweenBuildingsParams = new BetweenBuildingsParams();
                }
                return this.mBetweenBuildingsParams;
            }
        }
        
        public virtual GoToCanadaParams GoToCanadaParams
        {
            get
            {
                if ((this.mGoToCanadaParams == null))
                {
                    this.mGoToCanadaParams = new GoToCanadaParams();
                }
                return this.mGoToCanadaParams;
            }
        }
        
        public virtual FerryRunParams FerryRunParams
        {
            get
            {
                if ((this.mFerryRunParams == null))
                {
                    this.mFerryRunParams = new FerryRunParams();
                }
                return this.mFerryRunParams;
            }
        }
        
        public virtual FortSearchParams FortSearchParams
        {
            get
            {
                if ((this.mFortSearchParams == null))
                {
                    this.mFortSearchParams = new FortSearchParams();
                }
                return this.mFortSearchParams;
            }
        }
        
        public virtual WhitToSantaClaraParams WhitToSantaClaraParams
        {
            get
            {
                if ((this.mWhitToSantaClaraParams == null))
                {
                    this.mWhitToSantaClaraParams = new WhitToSantaClaraParams();
                }
                return this.mWhitToSantaClaraParams;
            }
        }
        
        public virtual WhitToScrippsParams WhitToScrippsParams
        {
            get
            {
                if ((this.mWhitToScrippsParams == null))
                {
                    this.mWhitToScrippsParams = new WhitToScrippsParams();
                }
                return this.mWhitToScrippsParams;
            }
        }
        
        public virtual WhitToSanDiegoParams WhitToSanDiegoParams
        {
            get
            {
                if ((this.mWhitToSanDiegoParams == null))
                {
                    this.mWhitToSanDiegoParams = new WhitToSanDiegoParams();
                }
                return this.mWhitToSanDiegoParams;
            }
        }
        
        public virtual EastWestParams EastWestParams
        {
            get
            {
                if ((this.mEastWestParams == null))
                {
                    this.mEastWestParams = new EastWestParams();
                }
                return this.mEastWestParams;
            }
        }
        
        public virtual OpenWazeWebsiteParams OpenWazeWebsiteParams
        {
            get
            {
                if ((this.mOpenWazeWebsiteParams == null))
                {
                    this.mOpenWazeWebsiteParams = new OpenWazeWebsiteParams();
                }
                return this.mOpenWazeWebsiteParams;
            }
        }
        
        public virtual OpenWaze2Params OpenWaze2Params
        {
            get
            {
                if ((this.mOpenWaze2Params == null))
                {
                    this.mOpenWaze2Params = new OpenWaze2Params();
                }
                return this.mOpenWaze2Params;
            }
        }
        
        public virtual Whitworth2Params Whitworth2Params
        {
            get
            {
                if ((this.mWhitworth2Params == null))
                {
                    this.mWhitworth2Params = new Whitworth2Params();
                }
                return this.mWhitworth2Params;
            }
        }
        
        public virtual Whitworth3Params Whitworth3Params
        {
            get
            {
                if ((this.mWhitworth3Params == null))
                {
                    this.mWhitworth3Params = new Whitworth3Params();
                }
                return this.mWhitworth3Params;
            }
        }
        
        public UITrafficJamNewsUpdateWindow UITrafficJamNewsUpdateWindow
        {
            get
            {
                if ((this.mUITrafficJamNewsUpdateWindow == null))
                {
                    this.mUITrafficJamNewsUpdateWindow = new UITrafficJamNewsUpdateWindow();
                }
                return this.mUITrafficJamNewsUpdateWindow;
            }
        }
        
        public UINewTabGoogleChromeWindow UINewTabGoogleChromeWindow
        {
            get
            {
                if ((this.mUINewTabGoogleChromeWindow == null))
                {
                    this.mUINewTabGoogleChromeWindow = new UINewTabGoogleChromeWindow();
                }
                return this.mUINewTabGoogleChromeWindow;
            }
        }
        #endregion
        
        #region Fields
        private SearchOnWhitworthParams mSearchOnWhitworthParams;
        
        private SearchOverSeasParams mSearchOverSeasParams;
        
        private GoToCubaParams mGoToCubaParams;
        
        private InterHawaiiParams mInterHawaiiParams;
        
        private GoToCostcoParams mGoToCostcoParams;
        
        private BetweenBuildingsParams mBetweenBuildingsParams;
        
        private GoToCanadaParams mGoToCanadaParams;
        
        private FerryRunParams mFerryRunParams;
        
        private FortSearchParams mFortSearchParams;
        
        private WhitToSantaClaraParams mWhitToSantaClaraParams;
        
        private WhitToScrippsParams mWhitToScrippsParams;
        
        private WhitToSanDiegoParams mWhitToSanDiegoParams;
        
        private EastWestParams mEastWestParams;
        
        private OpenWazeWebsiteParams mOpenWazeWebsiteParams;
        
        private OpenWaze2Params mOpenWaze2Params;
        
        private Whitworth2Params mWhitworth2Params;
        
        private Whitworth3Params mWhitworth3Params;
        
        private UITrafficJamNewsUpdateWindow mUITrafficJamNewsUpdateWindow;
        
        private UINewTabGoogleChromeWindow mUINewTabGoogleChromeWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SearchOnWhitworth'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class SearchOnWhitworthParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Whitworth ' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Whitworth ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SearchOverSeas'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class SearchOverSeasParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Whitworth {RShiftKey}University' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Whitworth {RShiftKey}University";
        
        /// <summary>
        /// Type 'London ' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "London ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'GoToCuba'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class GoToCubaParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Cuba {RShiftKey}Ha' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Cuba {RShiftKey}Ha";
        
        /// <summary>
        /// Type 'vana{Enter}' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "vana{Enter}";
        
        /// <summary>
        /// Type 'Florida {RShiftKey}Keys' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys2 = "Florida {RShiftKey}Keys";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'InterHawaii'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class InterHawaiiParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Marriot {RShiftKey}Ka' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Marriot {RShiftKey}Ka";
        
        /// <summary>
        /// Type 'Marriott ' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "Marriott ";
        
        /// <summary>
        /// Type 'Oahu' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys2 = "Oahu";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'GoToCostco'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class GoToCostcoParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Costco' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Costco";
        
        /// <summary>
        /// Type 'Whitworth ' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "Whitworth ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'BetweenBuildings'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class BetweenBuildingsParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Eric {RShiftKey}Johnston {RShiftKey}Science {RShiftKey}Center{Enter}' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Eric {RShiftKey}Johnston {RShiftKey}Science {RShiftKey}Center{Enter}";
        
        /// <summary>
        /// Type 'Robinson ' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "Robinson ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'GoToCanada'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class GoToCanadaParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Whitworth' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Whitworth";
        
        /// <summary>
        /// Type 'Nelson ' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "Nelson ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'FerryRun'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class FerryRunParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Seattle {RShiftKey}University' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Seattle {RShiftKey}University";
        
        /// <summary>
        /// Type 'whid' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "whid";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'FortSearch'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class FortSearchParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Parade {RShiftKey}Field' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Parade {RShiftKey}Field";
        
        /// <summary>
        /// Type 'Odenton {RShiftKey}Marc' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "Odenton {RShiftKey}Marc";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'WhitToSantaClara'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class WhitToSantaClaraParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Whitworth {RShiftKey}Univer' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Whitworth {RShiftKey}Univer";
        
        /// <summary>
        /// Type 'Santa {RShiftKey}Clara {RShiftKey}Un' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "Santa {RShiftKey}Clara {RShiftKey}Un";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'WhitToScripps'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class WhitToScrippsParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Whitworth {RShiftKey}University' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Whitworth {RShiftKey}University";
        
        /// <summary>
        /// Type 'Scripps {RShiftKey}Co' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "Scripps {RShiftKey}Co";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'WhitToSanDiego'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class WhitToSanDiegoParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Whitworth' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Whitworth";
        
        /// <summary>
        /// Type 'University of {RShiftKey}San {RShiftKey}D' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "University of {RShiftKey}San {RShiftKey}D";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'EastWest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class EastWestParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Whitworth {RShiftKey}University' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Whitworth {RShiftKey}University";
        
        /// <summary>
        /// Type 'University of {RShiftKey}Maryland' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "University of {RShiftKey}Maryland";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'OpenWazeWebsite'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class OpenWazeWebsiteParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'www.waze.com/livemap{Enter}' in 'Address and search bar' text box
        /// </summary>
        public string UIAddressandsearchbarEditSendKeys = "www.waze.com/livemap{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'OpenWaze2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class OpenWaze2Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'www.waze.com/livemap{Enter}' in 'Address and search bar' text box
        /// </summary>
        public string UIAddressandsearchbarEditSendKeys = "www.waze.com/livemap{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Whitworth2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class Whitworth2Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'Whitworth {RShiftKey}Univeri{Back}sity' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Whitworth {RShiftKey}Univeri{Back}sity";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Whitworth3'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class Whitworth3Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'www.waze.com/livemap{Enter}' in 'Address and search bar' text box
        /// </summary>
        public string UIAddressandsearchbarEditSendKeys = "www.waze.com/livemap{Enter}";
        
        /// <summary>
        /// Type 'Whitworth {RShiftKey}Un' in 'Address and search bar' text box
        /// </summary>
        public string UIAddressandsearchbarEditSendKeys1 = "Whitworth {RShiftKey}Un";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITrafficJamNewsUpdateWindow : WinWindow
    {
        
        public UITrafficJamNewsUpdateWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Traffic Jam News, Updates from the Road - Waze Live Map - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Traffic Jam News, Updates from the Road - Waze Live Map - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinWindow UITrafficJamNewsUpdateWindow1
        {
            get
            {
                if ((this.mUITrafficJamNewsUpdateWindow1 == null))
                {
                    this.mUITrafficJamNewsUpdateWindow1 = new WinWindow(this);
                    #region Search Criteria
                    this.mUITrafficJamNewsUpdateWindow1.SearchProperties[WinWindow.PropertyNames.Name] = "Traffic Jam News, Updates from the Road - Waze Live Map";
                    this.mUITrafficJamNewsUpdateWindow1.WindowTitles.Add("Traffic Jam News, Updates from the Road - Waze Live Map - Google Chrome");
                    #endregion
                }
                return this.mUITrafficJamNewsUpdateWindow1;
            }
        }
        
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        
        public UIChromeLegacyWindowWindow1 UIChromeLegacyWindowWindow1
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow1 == null))
                {
                    this.mUIChromeLegacyWindowWindow1 = new UIChromeLegacyWindowWindow1(this);
                }
                return this.mUIChromeLegacyWindowWindow1;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUITrafficJamNewsUpdateWindow1;
        
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        
        private UIChromeLegacyWindowWindow1 mUIChromeLegacyWindowWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Chrome Legacy Window";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_RenderWidgetHostHWND";
            this.WindowTitles.Add("Traffic Jam News, Updates from the Road - Waze Live Map - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Traffic Jam News, Updates from the Road - Waze Live Map - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIChromeLegacyWindowWindow1 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1269974944";
            this.WindowTitles.Add("Traffic Jam News, Updates from the Road - Waze Live Map - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Traffic Jam News, Updates from the Road - Waze Live Map - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UINewTabGoogleChromeWindow : WinWindow
    {
        
        public UINewTabGoogleChromeWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "New Tab - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("New Tab - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIItemGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup(this);
                }
                return this.mUIItemGroup;
            }
        }
        #endregion
        
        #region Fields
        private UIItemGroup mUIItemGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemGroup : WinGroup
    {
        
        public UIItemGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("New Tab - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchbarEdit
        {
            get
            {
                if ((this.mUIAddressandsearchbarEdit == null))
                {
                    this.mUIAddressandsearchbarEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchbarEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search bar";
                    this.mUIAddressandsearchbarEdit.WindowTitles.Add("New Tab - Google Chrome");
                    #endregion
                }
                return this.mUIAddressandsearchbarEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchbarEdit;
        #endregion
    }
}
