// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Waze
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Open Live Map
        /// </summary>
        public void GoToLiveMap()
        {
            #region Variable Declarations
            WinWindow uIFreeCommunitybasedMaWindow1 = this.UIFreeCommunitybasedMaWindow.UIFreeCommunitybasedMaWindow1;
            #endregion

            // Click 'Free Community-based Mapping, Traffic & Navigation...' window
            Mouse.Click(uIFreeCommunitybasedMaWindow1, new Point(643, 106));
        }
        
        /// <summary>
        /// Access the search bar and look for Whitworth
        /// </summary>
        public void LeaveFromCampus()
        {
            #region Variable Declarations
            WinWindow uITrafficJamNewsUpdateWindow1 = this.UITrafficJamNewsUpdateWindow.UITrafficJamNewsUpdateWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITrafficJamNewsUpdateWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(118, 188));

            // Type 'Whitworth {RShiftKey}{RShiftKey}University{Enter}' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.LeaveFromCampusParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Traffic Jam News, Updates from the Road - Waze Liv...' window
            Mouse.Click(uITrafficJamNewsUpdateWindow1, new Point(182, 227));
        }
        
        #region Properties
        public virtual LeaveFromCampusParams LeaveFromCampusParams
        {
            get
            {
                if ((this.mLeaveFromCampusParams == null))
                {
                    this.mLeaveFromCampusParams = new LeaveFromCampusParams();
                }
                return this.mLeaveFromCampusParams;
            }
        }
        
        public UIFreeCommunitybasedMaWindow UIFreeCommunitybasedMaWindow
        {
            get
            {
                if ((this.mUIFreeCommunitybasedMaWindow == null))
                {
                    this.mUIFreeCommunitybasedMaWindow = new UIFreeCommunitybasedMaWindow();
                }
                return this.mUIFreeCommunitybasedMaWindow;
            }
        }
        
        public UITrafficJamNewsUpdateWindow UITrafficJamNewsUpdateWindow
        {
            get
            {
                if ((this.mUITrafficJamNewsUpdateWindow == null))
                {
                    this.mUITrafficJamNewsUpdateWindow = new UITrafficJamNewsUpdateWindow();
                }
                return this.mUITrafficJamNewsUpdateWindow;
            }
        }
        #endregion
        
        #region Fields
        private LeaveFromCampusParams mLeaveFromCampusParams;
        
        private UIFreeCommunitybasedMaWindow mUIFreeCommunitybasedMaWindow;
        
        private UITrafficJamNewsUpdateWindow mUITrafficJamNewsUpdateWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LeaveFromCampus'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class LeaveFromCampusParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Whitworth {RShiftKey}{RShiftKey}University{Enter}' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "Whitworth {RShiftKey}{RShiftKey}University{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIFreeCommunitybasedMaWindow : WinWindow
    {
        
        public UIFreeCommunitybasedMaWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Free Community-based Mapping, Traffic & Navigation App - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Free Community-based Mapping, Traffic & Navigation App - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinWindow UIFreeCommunitybasedMaWindow1
        {
            get
            {
                if ((this.mUIFreeCommunitybasedMaWindow1 == null))
                {
                    this.mUIFreeCommunitybasedMaWindow1 = new WinWindow(this);
                    #region Search Criteria
                    this.mUIFreeCommunitybasedMaWindow1.SearchProperties[WinWindow.PropertyNames.Name] = "Free Community-based Mapping, Traffic & Navigation App";
                    this.mUIFreeCommunitybasedMaWindow1.WindowTitles.Add("Free Community-based Mapping, Traffic & Navigation App - Google Chrome");
                    #endregion
                }
                return this.mUIFreeCommunitybasedMaWindow1;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIFreeCommunitybasedMaWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITrafficJamNewsUpdateWindow : WinWindow
    {
        
        public UITrafficJamNewsUpdateWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Traffic Jam News, Updates from the Road - Waze Live Map - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Traffic Jam News, Updates from the Road - Waze Live Map - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinWindow UITrafficJamNewsUpdateWindow1
        {
            get
            {
                if ((this.mUITrafficJamNewsUpdateWindow1 == null))
                {
                    this.mUITrafficJamNewsUpdateWindow1 = new WinWindow(this);
                    #region Search Criteria
                    this.mUITrafficJamNewsUpdateWindow1.SearchProperties[WinWindow.PropertyNames.Name] = "Traffic Jam News, Updates from the Road - Waze Live Map";
                    this.mUITrafficJamNewsUpdateWindow1.WindowTitles.Add("Traffic Jam News, Updates from the Road - Waze Live Map - Google Chrome");
                    #endregion
                }
                return this.mUITrafficJamNewsUpdateWindow1;
            }
        }
        
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUITrafficJamNewsUpdateWindow1;
        
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Chrome Legacy Window";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_RenderWidgetHostHWND";
            this.WindowTitles.Add("Traffic Jam News, Updates from the Road - Waze Live Map - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Traffic Jam News, Updates from the Road - Waze Live Map - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
}
